### ISSUE TITLE
PHP FORM - Sign up

### ISSUE THREAD

**Issue by kingyeet9048** [kingyeet9048/math-tutor#11]
This form will accept the following information: First Name, Last Name, Username, Password, and Role. The star ID will be autogenerated. With this information, the database will be filled in. if the user is a student, percentCompleted will be initialized to 0 and courseID will be randomly assigned to a student. If no courses are available, the student cannot sign up. Return the appriote messages or errors. 

Don't forget to save the StarID as a session for later use. 

Stack - PHP
https://mnscu-my.sharepoint.com/:w:/g/personal/rp5626vi_go_minnstate_edu/ERdYDrGPSHhOlIUOVIqF52gBY6LOlnesIVU5QBSA2PYXkw?e=ejq5y2

**Comment by TheMinds3t** [comment]
@kingyeet9048 @nameer1811 where do I store the percentCompleted / what do I use to calculate that? I don't see any way to indicate questions completed by a student, or where to assign courses to students.

**Comment by kingyeet9048** [comment]
@TheMinds3t

- You can store the percentCompleted on the info table. It should be reflected on the mysql schema. 
- Would it help to change percentCompleted to numberCorrect?
- I believe the easiest way to calculate it is as the student completes the questions. We know that the questions are asked one by one. Depending on the question type, a specific question will be asked. If the user gets the question right, +1 would be added to the percentCompleted. If they get the question incorrect, a -1 would be removed from their percentCompleted. This means that you will be accepting requests on a per-question basis.

What do you think?
And of course, we can get the actual percent of completed course simply by doing percentCompleted / (Total questions assigned to class).

**Comment by kingyeet9048** [comment]
@TheMinds3t While working on the design for the course learning I realized something. This might have been what your question was. There no way to "save" the state of a current learning session. That means that we will know the number of completed questions, but we will not know which questions the student completes and where to continue after a next session. To combat this problem, I propose we remove the percentCompleted from the info table and add a questionsRight (varchar 500). This way, you can have questionIDs seperated by commas to know which numbers which students got right. Any question not on the questionsRight attribute is automatically assumed that the user got wrong or did not attempt yet. From this info, we can know the number of correct questions, and the save state by going to the largest number in questionsRight.

**Comment by TheMinds3t** [comment]
Why don't we just add a new "records" table to the db, with question number, star id, and course number? Then we add an entry when a question is complete, remove entries to wipe completion, and percent complete could easily be calculated. It'd be more scaleable than a single entry in an existing table at the least.

**Comment by kingyeet9048** [comment]
Ok I like that. Good thinking. One thing though. Still a little confused on why we would need to wipe completion?

**Comment by TheMinds3t** [comment]
We wouldn't, but it would be possible in a future addon (not for this assignment). Basically it isn't relevant to wipe completion, the only applicable instance I could see is if a student does a course again

**Comment by kingyeet9048** [comment]
That is what I was thinking too. We don't have that functionality. I do see your point though. It provides options to sale further than just an attribute on an existing table.

Anyways, hold off on the progress related issues. I will redo them just as soon as I make some issues for @nameer1811 to do.

**Comment by TheMinds3t** [comment]
Sounds good to me!

**Comment by kingyeet9048** [comment]
Edited the issues so they should be good to go. Let me know if they are understandable. I can reword if its not.

**Comment by TheMinds3t** [comment]
@kingyeet9048 we can close this right?

**Comment by kingyeet9048** [comment]
yes
