### ISSUE TITLE
PHP FORM - student progress (progress page)

### ISSUE THREAD

**Issue by kingyeet9048** [kingyeet9048/math-tutor#22]
uses star id to retrieve the courseName and percent of completed questions (number of correct questions divided by the total number of questions) of the current user. Return the output. If there is no course name and or the user has not gotten an questions correct, return null.

**Comment by TheMinds3t** [comment]
I'll write a PHP script for this, however this would be more efficiently done via a stored procedure. So the script will just connect the procedure with the PHP.
