### ISSUE TITLE
PHP FORM - all students taking class (progress page)

### ISSUE THREAD

**Issue by kingyeet9048** [kingyeet9048/math-tutor#23]
The star ID will be used to check the associated courseID (if this current teacher is teaching a class) and use the courseID to find all associated first names, and last names. Additionally, use the starID of each student associated with that current courseID to find the number of correct questions.

**Comment by TheMinds3t** [comment]
I'll write a PHP script for this, however this would be more efficiently done via a stored procedure. So the script will just connect the procedure with the PHP.
