### ISSUE TITLE
PHP FORM - Delete course (course teaching page)

### ISSUE THREAD

**Issue by kingyeet9048** [kingyeet9048/math-tutor#29]
Uses courseName to delete the course. This will also delete all student's courseID, records associated with that current class, and all questions associated with that course. Return results.

**Comment by nameer1811** [comment]
Do you want me to just create a stored procedure for this? This is going to be so much easier with just called a procedure from the database?

**Comment by kingyeet9048** [comment]
Yes, please do that

**Comment by TheMinds3t** [comment]
Sounds good. I'll write a PHP script for this, however this would be more efficiently done via a stored procedure. So the script will just connect the procedure with the PHP.

**Comment by TheMinds3t** [comment]
@kingyeet9048 what results do you want returned for this?

**Comment by kingyeet9048** [comment]
Whether the deletion was successful or not.

**Comment by TheMinds3t** [comment]
Check the latest PR in #46, this script exists in that version.
