### ISSUE TITLE
Create stored procedure for list of students enrolled in course.

### ISSUE THREAD

**Issue by TheMinds3t** [kingyeet9048/math-tutor#52]
The star ID will be used to check the associated courseID (if this current teacher is teaching a class) and use the courseID to find all associated first names, and last names. Additionally, use the starID of each student associated with that current courseID to find the number of correct questions.

**Comment by TheMinds3t** [comment]
getEnrolled(teacherStarID) sound good to you?

**Comment by nameer1811** [comment]
How are we keeping track of correct questions? How do you think I should implement it through the database?
