### ISSUE TITLE
PHP FORM - login page

### ISSUE THREAD

**Issue by kingyeet9048** [kingyeet9048/math-tutor#9]
https://mnscu-my.sharepoint.com/:w:/g/personal/rp5626vi_go_minnstate_edu/ERdYDrGPSHhOlIUOVIqF52gBY6LOlnesIVU5QBSA2PYXkw?e=ejq5y2

PHP form that takes username and password and checks it with the DB. 

Dont forget to save starID in the session. 

Stack - PHP

**Comment by TheMinds3t** [comment]
Added skeleton structure for login process

**Comment by kingyeet9048** [comment]
@TheMinds3t Save the star id in the session

**Comment by TheMinds3t** [comment]
@kingyeet9048 Star ID is saved in current master branch, can we resolve this?

**Comment by kingyeet9048** [comment]
@TheMinds3t Yes. Will close the issue now
